# Eureka 的集群方式配置, 互相发现
spring:
  application:
    name: ms-eureka-ha
  profiles:
    active: peer1
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8000/eureka/, http://peer2:8001/eureka/
logging:
  level:
    root: INFO
    org.springframework.cloud.sleuth: DEBUG
---
# 启动方式 java -jar xx.jar --spring.profiles.active=peer1
spring:
  profiles: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
#  server:
#    enable-self-preservation: false
---
# 启动方式 java -jar xx.jar --spring.profiles.active=peer1
spring:
  profiles: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  server:
#    关闭自我保护功能
#    enable-self-preservation: false