server:
  port: 8888
spring:
  application:
    name: ms-zuul
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://peer1:8000/eureka/, http://peer2:8001/eureka/
    instance:
      # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
      prefer-ip-address: true
zuul:
  routes:
    ms-movie-feign: /movie/**
    ms-user: /user/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always